[book]
authors = ["Adamkadaban"]
language = "en"
multilingual = false
src = "src"
title = "howtowincptc"


[output.html]
git-repository-url = "https://github.com/adamkadaban/howtowincptc"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/adamkadaban/howtowincptc/edit/main/{path}"

